### ISSUE TITLE
Bug inline menu when display diff

### ISSUE THREAD

**Issue by AlexVcht** [erwanlbp/trading-bot#27]
<img width="317" alt="image" src="https://github.com/erwanlbp/trading-bot/assets/29099155/3274326a-3771-45be-a7e8-2320cededf54">

**Comment by erwanlbp** [comment]
est ce qu'on a vraiment besoin de paginer à chaque fois mdrr au pire ca fait des "longs" messages mais ca reste simple à comprendre
